name = "Ruhas Mc Pack 1"
author = "ruha0987654321"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e943bfbab2e199ce33b631a8fcbb8d44661f8d5c7f8ebd14794d6a34fd37a3f8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
