name = "Ruhas Mc Pack 1"
author = "ruha0987654321"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5ad4e2d036e3184f9c15aff4a8bb7022c0ce6a4eb57fb454176616fb5674eae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
