name = "Ruhas Mc Pack 1"
author = "ruha0987654321"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d46f32755cab817714fdfdb31d23ea7438e625d52fcde4b53b2a0f61f65a2387"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"

[options]
acceptable-game-versions = ["1.21"]
